var fs = require('fs');
var content = fs.readFileSync('scoring.js', 'utf8');
var exportPos = content.indexOf('module.exports');

var v23 = [
'',
'// V23 - V16 + volumeRatio weight boost (0-8 -> 0-13)',
'// V16 has best 10d stats but 5d winrate low, likely due to low volumeRatio weight',
'function calcTechScoreV23(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData) {',
'  var score = 0',
'  var chg = stock.changePct || 0',
'  var isGem = code.startsWith(String.fromCharCode(51,48,48)) || code.startsWith(String.fromCharCode(51,48,49)) || code.startsWith(String.fromCharCode(54,56,56))',
'  var maSignal = techData ? (techData.maSignal || "neutral") : "neutral"',
'  var momentum20 = techData ? (techData.momentum20 || 0) : 0',
'  var ma5 = techData ? (techData.ma5 || 0) : 0',
'  var ma10 = techData ? (techData.ma10 || 0) : 0',
'  var ma20 = techData ? (techData.ma20 || 0) : 0',
'  var ma60 = techData ? (techData.ma60 || 0) : 0',
'  var macdObj = techData ? (techData.macdObj || {}) : {}',
'  var price = stock.price || 0',
'  var amplitude = stock.amplitude || 0',
'  var adx = techData ? (techData.adx || 0) : 0',
'  var plusDI = techData ? (techData.plusDI || 0) : 0',
'  var minusDI = techData ? (techData.minusDI || 0) : 0',
'  var obvTrend = techData ? (techData.obvTrend || 0) : 0',
'  var obvSlope5 = techData ? (techData.obvSlope5 || 0) : 0',
'  var ma5Slope = techData ? (techData.ma5Slope || 0) : 0',
'  var ma10Slope = techData ? (techData.ma10Slope || 0) : 0',
'  var atr = techData ? (techData.atr || 0) : 0',
'  var patterns = techData ? (techData.patterns || {}) : {}',
'',
'  // 1. chg(0-10) reduced from V16 0-12',
'  if (isGem) {',
'    if (chg >= 1.5 && chg <= 4) score += 10',
'    else if (chg >= 1 && chg < 1.5) score += 7',
'    else if (chg > 4 && chg <= 7) score += 5',
'    else if (chg > 7 && chg <= 10) score += 2',
'    else if (chg > 10) score += 1',
'    else if (chg >= 0 && chg < 1) score += 3',
'    else score += Math.max(0, 1 + chg)',
'  } else {',
'    if (chg >= 1.5 && chg <= 4) score += 10',
'    else if (chg >= 1 && chg < 1.5) score += 7',
'    else if (chg > 4 && chg <= 6) score += 4',
'    else if (chg > 6) score += 1',
'    else if (chg >= 0 && chg < 1) score += 3',
'    else score += Math.max(0, 1 + chg)',
'  }',
'',
'  // 2. volumeRatio(0-13) boosted from V16 0-8',
'  if (volumeRatio >= 1.5 && volumeRatio <= 2.5) score += 13',
'  else if (volumeRatio >= 1.0 && volumeRatio < 1.5) score += 9',
'  else if (volumeRatio > 2.5 && volumeRatio <= 4) score += 5',
'  else if (volumeRatio > 4 && volumeRatio <= 6) score += 2',
'  else if (volumeRatio > 6) score += 1',
'  else if (volumeRatio >= 0.5) score += 1',
'',
'  // 3. trend(0-12)',
'  var ts = 0',
'  if (maSignal === "bull") ts += 4',
'  if (price > 0 && ma5 > 0 && ma10 > 0) {',
'    if (price > ma5 && price > ma10) ts += 2',
'    else if (price > ma5 || price > ma10) ts += 1',
'  }',
'  if (goldenCross) ts += 3',
'  else if (macdObj.dif > 0 && macdObj.dea > 0) ts += 1',
'  if (change5d >= 5 && change5d <= 15) ts += 2',
'  else if (change5d >= 3) ts += 1',
'  if (momentum20 >= 5 && momentum20 <= 20) ts += 1',
'  score += ts',
'',
'  // 4. price-volume(0-8)',
'  var ps = 0',
'  if (chg >= 1 && volumeRatio >= 1.5 && maSignal === "bull") ps += 3',
'  else if (chg >= 1 && volumeRatio >= 1.5) ps += 1',
'  if (chg >= 1 && chg <= 4 && volumeRatio >= 1 && volumeRatio <= 2.5 && amplitude >= 2 && amplitude <= 6) ps += 3',
'  if (rsi < 50 && rsi > 30 && volumeRatio >= 1.5 && goldenCross) ps += 2',
'  score += ps',
'',
'  // 5. ADX(0-8)',
'  if (adx >= 30 && plusDI > minusDI) score += 8',
'  else if (adx >= 25 && plusDI > minusDI) score += 6',
'  else if (adx >= 20 && plusDI > minusDI) score += 4',
'  else if (adx >= 20) score += 2',
'  else if (adx >= 15 && plusDI > minusDI) score += 2',
'',
'  // 6. OBV(0-7)',
'  if (obvTrend === 1 && obvSlope5 > 0.1) score += 7',
'  else if (obvTrend === 1 && obvSlope5 > 0) score += 5',
'  else if (obvTrend === 1) score += 3',
'  else if (obvSlope5 > 0.1) score += 2',
'  else if (obvSlope5 < -0.1) score -= 3',
'',
'  // 7. ATR(0-5)',
'  if (atr > 0 && price > 0) {',
'    var atrPct = atr / price * 100',
'    if (atrPct >= 2 && atrPct <= 4) score += 5',
'    else if (atrPct >= 1.5 && atrPct < 2) score += 3',
'    else if (atrPct > 4 && atrPct <= 5) score += 2',
'    else if (atrPct > 5) score -= 1',
'  }',
'',
'  // 8. MA slope(0-5)',
'  if (ma5Slope > 0.3 && ma10Slope > 0.2) score += 5',
'  else if (ma5Slope > 0.2 && ma10Slope > 0.1) score += 3',
'  else if (ma5Slope > 0.1 && ma10Slope > 0) score += 2',
'  else if (ma5Slope < -0.3) score -= 2',
'',
'  // 9. pattern(0-10) reduced from V16 0-15',
'  var pt = (patterns.cupHandle || 0) + (patterns.breakout || 0) + (patterns.pullbackRestart || 0) + (patterns.consecutiveUp || 0) + (patterns.bottomReversal || 0) + (patterns.maSupport || 0)',
'  score += Math.min(10, pt)',
'',
'  // 10. amplitude(0-3)',
'  if (amplitude >= 3 && amplitude <= 6) score += 3',
'  else if (amplitude >= 2 && amplitude < 3) score += 1',
'',
'  // 11. RSI(0-4)',
'  if (rsi >= 50 && rsi <= 65) score += 4',
'  else if (rsi >= 40 && rsi < 50) score += 2',
'  else if (rsi > 65 && rsi <= 75) score += 1',
'',
'  // 12. BOLL(0-3)',
'  if (bollPosition >= 0.5 && bollPosition < 0.8) score += 3',
'  else if (bollPosition >= 0.3 && bollPosition < 0.5) score += 1',
'',
'  // 13. fundamental(0-5)',
'  var f = 0',
'  if ((stock.roe || 0) >= 15) f += 2',
'  else if ((stock.roe || 0) >= 10) f += 1',
'  if (stock.pe > 0 && stock.pe <= 25) f += 2',
'  else if (stock.pe > 25 && stock.pe <= 40) f += 1',
'  if ((stock.debtRatio || 0) > 0 && stock.debtRatio <= 50) f += 1',
'  score += f',
'',
'  // 14. resonance(0-2) reduced from V16 0-5',
'  var rc = 0',
'  if (chg >= 1.5 && chg <= 4) rc++',
'  if (volumeRatio >= 1.5 && volumeRatio <= 2.5) rc++',
'  if (maSignal === "bull") rc++',
'  if (adx >= 20 && plusDI > minusDI) rc++',
'  if (obvTrend === 1) rc++',
'  if (rc >= 5) score += 2',
'  else if (rc >= 4) score += 1',
'',
'  // 15. risk filter same as V16',
'  if (chg > 6 && volumeRatio > 4) score -= 5',
'  if (rsi > 78) score -= 4',
'  if (change5d > 20) score -= 3',
'  if (maSignal === "bear") score -= 5',
'  if (ma60 > 0 && price > ma60 * 1.3) score -= 2',
'  if (obvTrend === -1 && chg > 3) score -= 3',
'',
'  return Math.round(Math.min(100, Math.max(0, score)))',
'}',
'',
].join(String.fromCharCode(10));

var newContent = content.substring(0, exportPos) + v23 + content.substring(exportPos);
fs.writeFileSync('scoring.js', newContent, 'utf8');
console.log('V23 added');
