var fs = require('fs');
var content = fs.readFileSync('scoring.js', 'utf8');
var exportPos = content.indexOf('module.exports');

var code = [
'',
'// V24 - V10 + momentum filter (not bonus, but hard filter)',
'// Require ADX confirmation or OBV uptrend, keep V10 score distribution',
'function calcTechScoreV24(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData) {',
'  var adx = techData ? (techData.adx || 0) : 0',
'  var plusDI = techData ? (techData.plusDI || 0) : 0',
'  var minusDI = techData ? (techData.minusDI || 0) : 0',
'  var obvTrend = techData ? (techData.obvTrend || 0) : 0',
'  var obvSlope5 = techData ? (techData.obvSlope5 || 0) : 0',
'  // Must have momentum confirmation: ADX>=20 & +DI>-DI OR OBV uptrend',
'  var hasADX = adx >= 20 && plusDI > minusDI',
'  var hasOBV = obvTrend === 1 || obvSlope5 > 0',
'  if (!hasADX && !hasOBV) return 0',
'  return calcTechScoreV10(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData)',
'}',
'',
'// V25 - V10 + volumeRatio weight boost (0-15 -> 0-18)',
'// Boost volumeRatio from 15 to 18, reduce trend from 25 to 22',
'function calcTechScoreV25(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData) {',
'  var score = 0',
'  var chg = stock.changePct || 0',
'  var isGem = code.startsWith("300") || code.startsWith("301") || code.startsWith("688")',
'  var maSignal = techData ? (techData.maSignal || "neutral") : "neutral"',
'  var momentum20 = techData ? (techData.momentum20 || 0) : 0',
'  var ma5 = techData ? (techData.ma5 || 0) : 0',
'  var ma10 = techData ? (techData.ma10 || 0) : 0',
'  var ma20 = techData ? (techData.ma20 || 0) : 0',
'  var macdObj = techData ? (techData.macdObj || {}) : {}',
'  var price = stock.price || 0',
'  var amplitude = stock.amplitude || 0',
'',
'  // 1. chg(0-20) same as V10',
'  if (isGem) {',
'    if (chg >= 1.5 && chg <= 4) score += 20',
'    else if (chg >= 1 && chg < 1.5) score += 16',
'    else if (chg > 4 && chg <= 7) score += 14',
'    else if (chg > 7 && chg <= 10) score += 8',
'    else if (chg > 10) score += 3',
'    else if (chg >= 0 && chg < 1) score += 8',
'    else if (chg < 0) score += Math.max(0, 2 + chg)',
'  } else {',
'    if (chg >= 1.5 && chg <= 4) score += 20',
'    else if (chg >= 1 && chg < 1.5) score += 16',
'    else if (chg > 4 && chg <= 6) score += 12',
'    else if (chg > 6) score += 3',
'    else if (chg >= 0 && chg < 1) score += 8',
'    else if (chg < 0) score += Math.max(0, 2 + chg)',
'  }',
'',
'  // 2. volumeRatio(0-18) boosted from V10 0-15',
'  if (volumeRatio >= 1.5 && volumeRatio <= 2.5) score += 18',
'  else if (volumeRatio >= 1.0 && volumeRatio < 1.5) score += 12',
'  else if (volumeRatio > 2.5 && volumeRatio <= 4) score += 10',
'  else if (volumeRatio > 4 && volumeRatio <= 6) score += 5',
'  else if (volumeRatio > 6) score += 1',
'  else if (volumeRatio >= 0.5 && volumeRatio < 1.0) score += 3',
'',
'  // 3. trend(0-22) reduced from V10 0-25',
'  var trendScore = 0',
'  if (maSignal === "bull") trendScore += 7',
'  if (price > 0 && ma5 > 0 && ma10 > 0) {',
'    if (price > ma5 && price > ma10) trendScore += 5',
'    else if (price > ma5 || price > ma10) trendScore += 2',
'  }',
'  if (goldenCross) trendScore += 4',
'  else if (macdObj.dif > 0 && macdObj.dea > 0) trendScore += 2',
'  if (change5d >= 5 && change5d <= 15) trendScore += 3',
'  else if (change5d >= 3 && change5d < 5) trendScore += 2',
'  else if (change5d >= 15 && change5d <= 25) trendScore += 1',
'  if (momentum20 >= 8 && momentum20 <= 25) trendScore += 3',
'  else if (momentum20 >= 3 && momentum20 < 8) trendScore += 1',
'  score += Math.min(22, trendScore)',
'',
'  // 4-8 same as V10',
'  var patternScore = 0',
'  if (chg >= 1 && volumeRatio >= 1.5 && maSignal === "bull") patternScore += 6',
'  else if (chg >= 1 && volumeRatio >= 1.5) patternScore += 3',
'  if (chg >= 1 && chg <= 4 && volumeRatio >= 1 && volumeRatio <= 2.5 && amplitude >= 2 && amplitude <= 6) patternScore += 5',
'  if (rsi < 50 && rsi > 30 && volumeRatio >= 1.5 && goldenCross) patternScore += 4',
'  score += patternScore',
'',
'  if (amplitude >= 3 && amplitude <= 6) score += 5',
'  else if (amplitude >= 2 && amplitude < 3) score += 3',
'  else if (amplitude > 6 && amplitude <= 8) score += 2',
'',
'  if (rsi >= 50 && rsi <= 65) score += 5',
'  else if (rsi >= 40 && rsi < 50) score += 3',
'  else if (rsi > 65 && rsi <= 75) score += 2',
'  else if (rsi > 75) score -= 2',
'',
'  if (bollPosition >= 0.5 && bollPosition < 0.8) score += 5',
'  else if (bollPosition >= 0.3 && bollPosition < 0.5) score += 3',
'  else if (bollPosition >= 0.8) score += 2',
'',
'  var fundamental = 0',
'  if ((stock.roe || 0) >= 15) fundamental += 4',
'  else if ((stock.roe || 0) >= 10) fundamental += 2',
'  if (stock.pe > 0 && stock.pe <= 25) fundamental += 3',
'  else if (stock.pe > 25 && stock.pe <= 40) fundamental += 1',
'  if ((stock.debtRatio || 0) > 0 && stock.debtRatio <= 50) fundamental += 3',
'  else if ((stock.debtRatio || 0) > 50 && stock.debtRatio <= 70) fundamental += 1',
'  score += fundamental',
'',
'  return Math.round(Math.min(100, Math.max(0, score)))',
'}',
'',
'// V26 - V25 score + V24 momentum filter',
'function calcTechScoreV26(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData) {',
'  var adx = techData ? (techData.adx || 0) : 0',
'  var plusDI = techData ? (techData.plusDI || 0) : 0',
'  var minusDI = techData ? (techData.minusDI || 0) : 0',
'  var obvTrend = techData ? (techData.obvTrend || 0) : 0',
'  var obvSlope5 = techData ? (techData.obvSlope5 || 0) : 0',
'  var hasADX = adx >= 20 && plusDI > minusDI',
'  var hasOBV = obvTrend === 1 || obvSlope5 > 0',
'  if (!hasADX && !hasOBV) return 0',
'  return calcTechScoreV25(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData)',
'}',
'',
].join(String.fromCharCode(10));

var newContent = content.substring(0, exportPos) + code + content.substring(exportPos);
// Add V24, V25, V26 to exports
newContent = newContent.replace('module.exports = {\n  calcTechScoreV22,', 'module.exports = {\n  calcTechScoreV24,\n  calcTechScoreV25,\n  calcTechScoreV26,\n  calcTechScoreV22,');
fs.writeFileSync('scoring.js', newContent, 'utf8');
console.log('V24/V25/V26 added');
