var fs = require('fs');
var content = fs.readFileSync('D:/wx_jztz/backtest/run_v78.js', 'utf8');

var strategies = [
"// V78策略: MACD金叉确认深度优化",
"// 核心发现: MACD金叉确认(WR=86.49% AR=4.31%)最有效但n=37太少",
"// 方法: MACD金叉确认+放宽boll/涨幅/量比+2天采样+多种止盈组合",
"var V78_STRATEGIES = {",
"  // 基准复现",
"  'v78_v73base': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 65, patternWeight: 2.0,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.8, adxMin: 25, rsiMax: 60",
"  }),",
"  'v78_v76macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 60, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"",
"  // === 放宽boll宽度 + MACD金叉 ===",
"  'v78_bw10_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 58, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"  'v78_bw10_macd_4710': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 58, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 4, trailingPct: 1 }, { profitPct: 7, trailingPct: 2 }, { profitPct: 10, trailingPct: 3 }]",
"  }),",
"  'v78_bw11_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.11,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"  'v78_bw11_macd_4710': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.11,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 4, trailingPct: 1 }, { profitPct: 7, trailingPct: 2 }, { profitPct: 10, trailingPct: 3 }]",
"  }),",
"",
"  // === 放宽涨幅 + MACD金叉 ===",
"  'v78_chg1_3_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 58, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 1, chgMax: 3, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"  'v78_chg1_3_macd_4710': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 58, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 1, chgMax: 3, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 4, trailingPct: 1 }, { profitPct: 7, trailingPct: 2 }, { profitPct: 10, trailingPct: 3 }]",
"  }),",
"  'v78_chg05_3_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 0.5, chgMax: 3, vrMin: 1.5, rsiMax: 65,",
"    confirmMACD: true",
"  }),",
"",
"  // === boll+涨幅组合 + MACD金叉 ===",
"  'v78_bw10_chg1_3_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 3, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"  'v78_bw10_chg1_3_macd_4710': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 3, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 4, trailingPct: 1 }, { profitPct: 7, trailingPct: 2 }, { profitPct: 10, trailingPct: 3 }]",
"  }),",
"",
"  // === 双重确认: ADX+MACD ===",
"  'v78_bw10_adx25_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmADX: 25, confirmMACD: true",
"  }),",
"  'v78_bw10_adx25_macd_4710': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmADX: 25, confirmMACD: true,",
"    trailingRules: [{ profitPct: 4, trailingPct: 1 }, { profitPct: 7, trailingPct: 2 }, { profitPct: 10, trailingPct: 3 }]",
"  }),",
"",
"  // === 放宽量比 + MACD金叉 ===",
"  'v78_vr12_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.2, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"  'v78_bw10_vr12_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 55, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.2, rsiMax: 60,",
"    confirmMACD: true",
"  }),",
"",
"  // === 宽止盈组合 ===",
"  'v78_bw09_macd_5811': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 60, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 5, trailingPct: 1.5 }, { profitPct: 8, trailingPct: 2.5 }, { profitPct: 11, trailingPct: 3.5 }]",
"  }),",
"  'v78_bw09_macd_6912': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 60, patternWeight: 2.0, bollWidthMax: 0.09,",
"    chgMin: 1, chgMax: 2.5, vrMin: 1.5, rsiMax: 60,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 6, trailingPct: 2 }, { profitPct: 9, trailingPct: 3 }, { profitPct: 12, trailingPct: 4 }]",
"  }),",
"",
"  // === 最宽松组合 ===",
"  'v78_bw10_chg1_3_vr12_macd': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 50, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 3, vrMin: 1.2, rsiMax: 65,",
"    confirmMACD: true",
"  }),",
"  'v78_bw10_chg1_3_vr12_macd_4710': Object.assign({}, BASE_EXIT, {",
"    ma5Min: 0.1, ma10Min: 0.02, requirePattern: 'boll_squeeze',",
"    minScore: 50, patternWeight: 2.0, bollWidthMax: 0.10,",
"    chgMin: 1, chgMax: 3, vrMin: 1.2, rsiMax: 65,",
"    confirmMACD: true,",
"    trailingRules: [{ profitPct: 4, trailingPct: 1 }, { profitPct: 7, trailingPct: 2 }, { profitPct: 10, trailingPct: 3 }]",
"  }),",
"}",
""
].join('\n');

var marker = "// V76策略: 在V75最佳结果基础上精细搜索\n\nasync function runBacktest()";
var idx = content.indexOf(marker);
if (idx === -1) {
  console.log('ERROR: marker not found');
  process.exit(1);
}

content = content.replace(marker, strategies + "async function runBacktest()");
fs.writeFileSync('D:/wx_jztz/backtest/run_v78.js', content, 'utf8');
console.log('SUCCESS: V78 strategies inserted');
console.log('New file size: ' + content.length + ' chars');
