var fs = require("fs");
var content = fs.readFileSync("scoring.js", "utf8");
var exportPos = content.indexOf("module.exports");

var v22 = [];
v22.push("");
v22.push("// V22 - V10 + ADX/OBV momentum confirm(0-8) + risk filter");
v22.push("// Keep V10 structure, add small confirm bonus, avoid score distortion");
v22.push("function calcTechScoreV22(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData) {");
v22.push("  var baseScore = calcTechScoreV10(stock, rsi, goldenCross, volumeRatio, bollPosition, code, change5d, techData)");
v22.push("  var bonus = 0");
v22.push("  var adx = techData ? (techData.adx || 0) : 0");
v22.push("  var plusDI = techData ? (techData.plusDI || 0) : 0");
v22.push("  var minusDI = techData ? (techData.minusDI || 0) : 0");
v22.push("  var obvTrend = techData ? (techData.obvTrend || 0) : 0");
v22.push("  var obvSlope5 = techData ? (techData.obvSlope5 || 0) : 0");
v22.push("  var chg = stock.changePct || 0");
v22.push("  var maSignal = techData ? (techData.maSignal || \"neutral\") : \"neutral\"");
v22.push("");
v22.push("  // momentum confirm bonus(0-8)");
v22.push("  if (adx >= 25 && plusDI > minusDI) bonus += 4");
v22.push("  else if (adx >= 20 && plusDI > minusDI) bonus += 2");
v22.push("  if (obvTrend === 1 && obvSlope5 > 0.1) bonus += 4");
v22.push("  else if (obvTrend === 1) bonus += 2");
v22.push("  else if (obvSlope5 > 0.1) bonus += 2");
v22.push("");
v22.push("  // risk filter penalty");
v22.push("  if (chg > 6 && volumeRatio > 4) bonus -= 5");
v22.push("  if (rsi > 78) bonus -= 4");
v22.push("  if (change5d > 20) bonus -= 3");
v22.push("  if (maSignal === \"bear\") bonus -= 5");
v22.push("  if (obvTrend === -1 && chg > 3) bonus -= 3");
v22.push("");
v22.push("  return Math.round(Math.min(100, Math.max(0, baseScore + bonus)))");
v22.push("}");
v22.push("");

var v22Code = v22.join(String.fromCharCode(10));
var newContent = content.substring(0, exportPos) + v22Code + content.substring(exportPos);
fs.writeFileSync("scoring.js", newContent, "utf8");
console.log("V22 added");