var fs = require('fs');
var content = fs.readFileSync('D:\\wx_jztz\\backtest\\indicators.js', 'utf8');
var exportIdx = content.lastIndexOf('module.exports');
if (exportIdx === -1) { console.log('ERROR: no module.exports'); process.exit(1); }

var newCode = "\n";
newCode += "// ===== V31: Volume-Price Coordination (0-100) =====\n";
newCode += "function calcVolumePriceCoord(klines) {\n";
newCode += "  if (!klines || klines.length < 10) return { score: 50, trend: 'neutral' }\n";
newCode += "  var recent = klines.slice(-10)\n";
newCode += "  var upWithVol = 0, upNoVol = 0, downWithVol = 0, downNoVol = 0\n";
newCode += "  for (var i = 1; i < recent.length; i++) {\n";
newCode += "    var priceUp = recent[i].close > recent[i - 1].close\n";
newCode += "    var volUp = recent[i].volume > recent[i - 1].volume\n";
newCode += "    if (priceUp && volUp) upWithVol++\n";
newCode += "    else if (priceUp && !volUp) upNoVol++\n";
newCode += "    else if (!priceUp && volUp) downWithVol++\n";
newCode += "    else downNoVol++\n";
newCode += "  }\n";
newCode += "  var total = recent.length - 1\n";
newCode += "  var coordRatio = upWithVol / total\n";
newCode += "  var divergeRatio = upNoVol / total\n";
newCode += "  var score = 50\n";
newCode += "  if (coordRatio >= 0.5) score = 80 + (coordRatio - 0.5) * 40\n";
newCode += "  else if (coordRatio >= 0.3) score = 60 + (coordRatio - 0.3) * 100\n";
newCode += "  else if (divergeRatio >= 0.5) score = 20\n";
newCode += "  else score = 40\n";
newCode += "  var trend = 'neutral'\n";
newCode += "  if (coordRatio >= 0.4) trend = 'bullish'\n";
newCode += "  else if (divergeRatio >= 0.4) trend = 'bearish_divergence'\n";
newCode += "  return { score: Math.min(100, Math.max(0, Math.round(score))), trend: trend, upWithVol: upWithVol, upNoVol: upNoVol }\n";
newCode += "}\n\n";

newCode += "// ===== V31: Trend Acceleration =====\n";
newCode += "function calcTrendAcceleration(closes) {\n";
newCode += "  if (!closes || closes.length < 20) return { accelerating: false, score: 0, accelRatio: 0 }\n";
newCode += "  var recentSlope = calcMASlope(closes, 5)\n";
newCode += "  var prevCloses = closes.slice(0, -3)\n";
newCode += "  var prevSlope = calcMASlope(prevCloses, 5)\n";
newCode += "  if (prevSlope === 0 && recentSlope === 0) return { accelerating: false, score: 0, accelRatio: 0 }\n";
newCode += "  var accelRatio = (recentSlope - prevSlope) / (Math.abs(prevSlope) || 0.001)\n";
newCode += "  var accelerating = false\n";
newCode += "  var score = 0\n";
newCode += "  if (recentSlope > 0 && accelRatio > 0.5) {\n";
newCode += "    accelerating = true\n";
newCode += "    if (accelRatio > 2) score = 100\n";
newCode += "    else if (accelRatio > 1) score = 80\n";
newCode += "    else score = 60\n";
newCode += "  } else if (recentSlope > 0 && accelRatio > 0) {\n";
newCode += "    score = 30\n";
newCode += "  }\n";
newCode += "  return { accelerating: accelerating, score: score, accelRatio: accelRatio, recentSlope: recentSlope, prevSlope: prevSlope }\n";
newCode += "}\n\n";

newCode += "// ===== V31: Consolidation Breakout (enhanced) =====\n";
newCode += "function detectConsolidationBreakout(klines) {\n";
newCode += "  if (!klines || klines.length < 25) return { detected: false, score: 0 }\n";
newCode += "  var recent = klines.slice(-25)\n";
newCode += "  var today = recent[recent.length - 1]\n";
newCode += "  var todayChg = (today.close - today.open) / today.open * 100\n";
newCode += "  var bestScore = 0\n";
newCode += "  for (var start = recent.length - 16; start <= recent.length - 6; start++) {\n";
newCode += "    if (start < 0) continue\n";
newCode += "    var range = recent.slice(start, -1)\n";
newCode += "    if (range.length < 5) continue\n";
newCode += "    var smallChgCount = 0\n";
newCode += "    var volDeclining = true\n";
newCode += "    var rangeHigh = -Infinity, rangeLow = Infinity\n";
newCode += "    for (var i = 0; i < range.length; i++) {\n";
newCode += "      var chg = Math.abs((range[i].close - range[i].open) / range[i].open * 100)\n";
newCode += "      if (chg <= 2.5) smallChgCount++\n";
newCode += "      rangeHigh = Math.max(rangeHigh, range[i].high)\n";
newCode += "      rangeLow = Math.min(rangeLow, range[i].low)\n";
newCode += "      if (i > 0 && range[i].volume > range[i - 1].volume * 1.1) volDeclining = false\n";
newCode += "    }\n";
newCode += "    var rangeAmplitude = (rangeHigh - rangeLow) / rangeLow * 100\n";
newCode += "    if (rangeAmplitude > 15) continue\n";
newCode += "    if (smallChgCount / range.length < 0.6) continue\n";
newCode += "    var breakout = today.close > rangeHigh && todayChg >= 1.5\n";
newCode += "    var avgVol = 0\n";
newCode += "    for (var i = 0; i < range.length; i++) avgVol += range[i].volume\n";
newCode += "    avgVol /= range.length\n";
newCode += "    var volRatio = avgVol > 0 ? today.volume / avgVol : 0\n";
newCode += "    var score = 0\n";
newCode += "    if (breakout && volRatio >= 1.5) score = 100\n";
newCode += "    else if (breakout && volRatio >= 1.2) score = 70\n";
newCode += "    else if (today.close > rangeHigh * 0.98 && todayChg >= 1 && volRatio >= 1.3) score = 50\n";
newCode += "    if (volDeclining && score > 0) score = Math.min(100, score + 10)\n";
newCode += "    if (score > bestScore) bestScore = score\n";
newCode += "  }\n";
newCode += "  return { detected: bestScore >= 50, score: bestScore }\n";
newCode += "}\n\n";

newCode += "// ===== V31: Candle Patterns =====\n";
newCode += "function calcCandlePatterns(klines) {\n";
newCode += "  if (!klines || klines.length < 5) return { score: 0, patterns: [] }\n";
newCode += "  var recent = klines.slice(-5)\n";
newCode += "  var today = recent[recent.length - 1]\n";
newCode += "  var score = 0\n";
newCode += "  var detected = []\n";
newCode += "  var todayBody = Math.abs(today.close - today.open)\n";
newCode += "  var todayRange = today.high - today.low\n";
newCode += "  if (today.close > today.open && todayRange > 0 && todayBody / todayRange > 0.7) {\n";
newCode += "    var avgVol = 0\n";
newCode += "    for (var i = 0; i < recent.length - 1; i++) avgVol += recent[i].volume\n";
newCode += "    avgVol /= (recent.length - 1)\n";
newCode += "    if (avgVol > 0 && today.volume / avgVol >= 1.5) { score += 12; detected.push('big_yang') }\n";
newCode += "  }\n";
newCode += "  if (recent.length >= 3) {\n";
newCode += "    var threeUp = true\n";
newCode += "    for (var i = recent.length - 3; i < recent.length; i++) {\n";
newCode += "      if (recent[i].close <= recent[i].open) { threeUp = false; break }\n";
newCode += "    }\n";
newCode += "    if (threeUp) { score += 8; detected.push('three_white') }\n";
newCode += "  }\n";
newCode += "  var lowerShadow = Math.min(today.open, today.close) - today.low\n";
newCode += "  if (todayRange > 0 && lowerShadow / todayRange > 0.4) { score += 5; detected.push('long_lower_shadow') }\n";
newCode += "  if (recent.length >= 2) {\n";
newCode += "    var gap = today.open - recent[recent.length - 2].close\n";
newCode += "    if (gap > 0 && today.close > today.open) { score += 6; detected.push('gap_up') }\n";
newCode += "  }\n";
newCode += "  return { score: Math.min(30, score), patterns: detected }\n";
newCode += "}\n\n";

var newContent = content.substring(0, exportIdx) + newCode + content.substring(exportIdx);
var oldExport = "detectConsecutiveUp, detectBottomReversal, detectMASupport,\n}";
var newExport = "detectConsecutiveUp, detectBottomReversal, detectMASupport,\n  calcVolumePriceCoord, calcTrendAcceleration, detectConsolidationBreakout, calcCandlePatterns,\n}";
newContent = newContent.replace(oldExport, newExport);
fs.writeFileSync('D:\\wx_jztz\\backtest\\indicators.js', newContent, 'utf8');
console.log('OK, length:', newContent.length);
